### ISSUE TITLE
SSL Support

### ISSUE THREAD

**Issue by robertmain** [robertmain/communique#16]
Communique does not currently have SSL support. This should be added in order to connect with many REST APIs

**Comment by delboy1978uk** [comment]
check this gist for ssl and curl 
https://gist.github.com/delboy1978uk/dcb8b9fb28eb64374ba7

**Comment by robertmain** [comment]
:+1: awesome, thankss - have you tested it yet(even without ssl support)? :)

**Comment by delboy1978uk** [comment]
not yet but i've been following the progress :-) 
will play with it when you've tagged a stable release version! :-D

**Comment by robertmain** [comment]
It's pretty much stable, but I'm hesitant to tag it as production ready without SSL support. So it's feature complete and stable, it just has no SSL support.

....yet.
