### ISSUE TITLE
Remove closures

### ISSUE THREAD

**Issue by robertmain** [robertmain/communique#17]
Remove the usage of the `$debug` closure as this will cause issues for servers running PHP <=5.3

**Comment by delboy1978uk** [comment]
i recommend dropping support - even 5.4 is EOL now

**Comment by robertmain** [comment]
Indeed, but some _ahem_ target systems are 5.2.9 :laughing:

**Comment by delboy1978uk** [comment]
oh god, really? if only the decision makers realised the security implications and lack of support... but theres no telling them lol!

**Comment by robertmain** [comment]
I think I'm gonna just leave it and make <=5.3 unsupported. Apart from anything else, I've had a look at guzzle and it looks to be a clone of what I'm building but better, so I'll probably end up just using that anyway.... Although I might continue with this on and off because it's a good learning exercise

**Comment by delboy1978uk** [comment]
possibly earlier versions of guzzle will work with 5.2, i think with composer you can set versions depending on the version of php! (never tried it, if you manage it, let me see the composer.json! ;-) )

**Comment by robertmain** [comment]
Perhaps I'll continue development of this until we move to newer servers\* and then replace it with guzzle

\* this probably won't happen in my lifetime

**Comment by robertmain** [comment]
Decided to drop support for PHP <=5.3.0
