### ISSUE TITLE
Custom cURL implementation

### ISSUE THREAD

**Issue by robertmain** [robertmain/communique#4]
Currently using a cURL library for the cURL implementation. It would be better to write a custom cURL implementation in order to have greater control over things like error handling (particularly with things like connection exceptions etc.)

**Comment by delboy1978uk** [comment]
better yet you should use guzzle. Its the best! http://guzzle.readthedocs.org/en/latest/

**Comment by robertmain** [comment]
I did wonder about it - but guzzle looks a bit high level, no?
