### ISSUE TITLE
issues with PHP 5.4 and 5.5

### ISSUE THREAD

**Issue by Remo** [robertmain/communique#50]
See this https://travis-ci.org/robertmain/communique/jobs/101440544
Personally I wouldn't care and simply remove those version from `.travis.yml`..

**Comment by Remo** [comment]
made a PR for this too if you want to remove them, also add hhvm: https://travis-ci.org/robertmain/communique/builds/101441174

**Comment by robertmain** [comment]
Whilst I approve of this and agree, I'm going to hang fire just yet until we've migrated away from the PHP 5.3 stack at work (going to 5.6). When that's done I'll look into merging it.

EDIT: on second thoughts, nevermind

**Comment by robertmain** [comment]
...on second
